import {render} from './utils/render.js';
import {generateTasksList} from './mock/task-mock.js';
import BoardComponent from './components/board.js';
import BoardController from './controllers/board-controller.js';
import FilterController from './controllers/filter-controller.js';
import SiteMenuComponent from './components/site-menu.js';
import TasksModel from './models/tasks-model.js';

const TASK_COUNT = 20;
const siteMain = document.querySelector(`.main`);
const siteHeader = siteMain.querySelector(`.main__control`);
const tasks = generateTasksList(TASK_COUNT);
const tasksModel = new TasksModel();
const boardComponent = new BoardComponent();
tasksModel.setTasks(tasks);
const boardController = new BoardController(boardComponent, tasksModel);
render(siteHeader, new SiteMenuComponent());
const filterController = new FilterController(siteMain, tasksModel);
filterController.render();
render(siteMain, boardComponent);
boardController.render(tasks);
